# Generated by Django 6.0.1 on 2026-02-03 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="post",
            old_name="author",
            new_name="user",
        ),
        migrations.AddField(
            model_name="post",
            name="image",
            field=models.ImageField(blank=True, null=True, upload_to="posts/"),
        ),
        migrations.AlterField(
            model_name="post",
            name="content",
            field=models.TextField(blank=True),
        ),
    ]
